services:
  - type: web
    name: wpp
    env: node
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildpacks:
      - heroku/nodejs
