services:
  - type: web
    name: wpp
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    buildpacks:
      - https://github.com/jontewks/puppeteer-heroku-buildpack
      - heroku/nodejs
